#!/bin/bash
helper(){
		while true; do
       echo "Please choose what you would like to do:"
        echo "i) List server information as shown on login (MOTD)"
				echo "m) Core Repo Installation - tag"
				echo "c) Community Repo Installation -tag"
				echo "l) List available tags to install"
				echo "d) Dedupe via plex_dupefinder"
				echo "u) Cloudplow upload"
				echo "e) Exit"
				read  -n 1 -p "Make a selection:" helperinput
				[[ -z $helperinput ]] && break
			echo $'\n'
				case $helperinput in
            i)
              cat /var/run/motd.dynamic
              ;;
						m)
							echo "Core Repo Installation Begining"
							echo "Which application would you like to install?"
							read -p "Enter Tag Name:" tag
							cd ~/cloudbox && sudo ansible-playbook cloudbox.yml --tags $tag
							;;
						c)
							echo "Community Repo Installation Begining"
							echo "Which application would you like to install?"
							read -p "Enter Tag Name:" tag
							cd ~/community && sudo ansible-playbook community.yml --tags $tag
							;;
						l)
							echo "All available cloudbox tags:"
              cd ~/cloudbox &&sudo ansible-playbook cloudbox.yml --list-tags 2>&1 | grep "TASK TAGS" | cut -d":" -f2 | awk '{sub(/\[/, "")sub(/\]/, "")}1' | sed -e 's/,//g' | xargs -n 1 | sort -u
							;;
						d)
							echo "plex_dupefinder Begining"
              plex_dupefinder
							;;
						u)
							nohup cloudplow upload > /opt/cloudplow/myupload.log &
							;;
						e)
							exit
							;;
						*)
							echo "Passed Variables= $helperinput $1 $2 $3"
							exit
							;;
					esac
			done
	}
cloudbox(){
	case $1 in
    i)
      cat /var/run/motd.dynamic
      ;;
		m)
			echo "Core Repo Installation Begining"
			cd ~/cloudbox && sudo ansible-playbook cloudbox.yml --tags $2
			;;
		c)
			echo "Community Repo Installation Begining"
			cd ~/community && sudo ansible-playbook community.yml --tags $2
			;;
    l)
      echo "All available cloudbox tags:"
      cd ~/cloudbox &&sudo ansible-playbook cloudbox.yml --list-tags 2>&1 | grep "TASK TAGS" | cut -d":" -f2 | awk '{sub(/\[/, "")sub(/\]/, "")}1' | sed -e 's/,//g' | xargs -n 1 | sort -u
      ;;
		d)
      echo "plex_dupefinder Begining"
      plex_dupefinder
			;;
		u)
			nohup cloudplow upload > /opt/cloudplow/myupload.log &
			;;
		*)
			#echo Welcome to Cloudbox Commandarr.
      cat << "EOF"
      _________ .__                   .______.
      \_   ___ \|  |   ____  __ __  __| _/\_ |__   _______  ___
      /    \  \/|  |  /  _ \|  |  \/ __ |  | __ \ /  _ \  \/  /
      \     \___|  |_(  <_> )  |  / /_/ |  | \_\ (  <_> >    <
       \______  /____/\____/|____/\____ |  |___  /\____/__/\_ \
              \/                       \/      \/            \/
      _________                                           .___
      \_   ___ \  ____   _____   _____ _____    ____    __| _/____ ______________
      /    \  \/ /  _ \ /     \ /     \\__  \  /    \  / __ |\__  \\_  __ \_  __ \
      \     \___(  <_> )  Y Y  \  Y Y  \/ __ \|   |  \/ /_/ | / __ \|  | \/|  | \/
       \______  /\____/|__|_|  /__|_|  (____  /___|  /\____ |(____  /__|   |__|
              \/             \/      \/     \/     \/      \/     \/

#########################################################################
# Author:   TRiCAM                                                      #
# URL:      https://github.com/tricamtech/cloudbox-commandarr           #
# --                                                                    #
#         Made for the Cloudbox project: https://cloudbox.works         #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################


EOF

			helper
			;;
	esac

	}

## Call the main function
cloudbox $1 $2 $3

## Do after cloudbox():
echo "We have finished. Have a nice day!"
